extends Control

const TICKS_TIME_MAX = 100 # msec

onready var current_scene = null
onready var current_scene_int = null
onready var loader = null
onready var wait_frames = 1
onready var database = null
onready var loaded = false
onready var animation = Loading.get_node("AnimLoading")

func _ready():
	database = load("res://scripts/Database.gd").new().initialize()
	
	_initialize_current_scene()
	_initialize_loading_scene()

func _initialize_loading_scene():
	animation.connect("animation_started", Event, "_loading_is_started")
	animation.connect("animation_finished", Event, "_loading_is_finished")

func goto_scene(path):
	print("[global#goto_scene] : load scene "+String(path))
	loader = ResourceLoader.load_interactive(path)
	if loader == null:
		print("Error loading ....")
		return

	Loading.show()
	animation.play("BorderAnim")
	
	set_process(true)
	current_scene.queue_free()
	wait_frames = 1
	Loading.get_node("LoadingBare/VBoxContainer/HBoxContainer/ProgressBar").set_max(loader.get_stage_count())

func _process(_delta):
	if loader == null:
		set_process(false)
		return
	
	if wait_frames > 0:
		wait_frames -= 1
	
	var tick = OS.get_ticks_msec()
	
	# Use "TICKS_TIME_MAX" to control for how long we block this thread
	while OS.get_ticks_msec() < tick + TICKS_TIME_MAX:
		if loaded:
			var err = loader.poll()
		
			if err == ERR_FILE_EOF: # Finished loading.
				_set_new_scene()
				break
			elif err == OK:
				_update_progress()
			else:
				loader = null
				break

## PRIVATE
func _initialize_current_scene():
	print("[global#_initialize_current_scene]")
	var root = get_tree().get_root()
	current_scene = root.get_child(root.get_child_count() - 1)
	
	if current_scene.name != "Main":
		get_node("/root/Loading").hide()

func _update_progress():
	Loading.visible = true
	Loading.get_node("LoadingBare/VBoxContainer/HBoxContainer/ProgressBar").set_value(loader.get_stage())

func _set_new_scene():
	var resource = loader.get_resource()
	loader = null
	current_scene = resource.instance()
	get_node("/root").add_child(current_scene)
	Loading.hide()
